#!/bin/sh

###############################################################################
# Functions
###############################################################################

get_script_dir()
{
    old_pwd=$PWD
    cd $(dirname "$1")
    XTF_ROOT=$(pwd)
    cd $old_pwd
}

get_results_file()
{
    dir=${HOME}/XTF_run/XTF_run_$(date '+%Y%m%d%H%M%S')
    mkdir -p ${dir}
    XTF_results=${dir}/results.qmr
}

get_script_dir $0
get_results_file

./qmtest/qmtest-xtf run -c XTF_ROOT=${XTF_ROOT} -o ${XTF_results}
RESULT=$?

case ${RESULT} in
0)
    echo "SUCCESS"
    ;;
*)
    echo "FAIL"
    echo $RESULT
esac
